name: Build, Test

on:	
  push:	
    branches-ignore:	
    - master	

jobs:	

  build:	
    name: Build, Test and Package	
    runs-on: ubuntu-18.04	

    steps:	
      - name: Set up JDK 1.8	
        uses: actions/setup-java@v1	
        with:	
          java-version: 1.8	
      - name: Checkout	
        uses: actions/checkout@v1
      - name: Test and Package
        run: mvn package war:war