name: Build Feature Branch

on:
  push:
    branches-ignore:
    - master

jobs:

  build:
    name: Build, Test and Package
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Checkout
      uses: actions/checkout@v1
    - name: Unit tests
      run: mvn test
    - name: Package
      run: mvn package war:war -Dmaven.test.skip=true
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/$GITHUB_REPOSITORY/bookstore:$GITHUB_SHA
    - name: Publish to GitHub Package Registry
      env:
        DOCKER_TOKEN: ${{secrets.GPR_TOKEN}}
        DOCKER_USER: <token>
      run: |
        docker login docker.pkg.github.com -u $DOCKER_USER -p $DOCKER_TOKEN
        docker push docker.pkg.github.com/$GITHUB_REPOSITORY/bookstore:$GITHUB_SHA

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
