name: Build, Test, Package and Deploy to Production!!!!

on:
  push:
    branches:
      - master

jobs:

  build:
    name: Build, Test and Package
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Checkout
        uses: actions/checkout@v1
      - name: Unit tests
        run: mvn test
      - name: Package
        run: mvn package war:war -Dmaven.test.skip=true
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag docker.pkg.github.com/$GITHUB_REPOSITORY/bookstore:$GITHUB_SHA
      - name: Publish to GitHub Package Registry
        env:
          DOCKER_TOKEN: ${{secrets.GPR_TOKEN}}
          DOCKER_USER: <token>
        run: |
          docker login docker.pkg.github.com -u $DOCKER_USER -p $DOCKER_TOKEN
          docker push docker.pkg.github.com/$GITHUB_REPOSITORY/bookstore:$GITHUB_SHA

  deploy:
    name: Deploy to Azure Container WebApp
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - name: Checking out the code
      uses: actions/checkout@v1
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy the container
      uses: azure/appservice-actions/webapp-container@master
      with:
        app-name: bookstore-prod
        images: ${{ format('{0}/{1}/{2}:{3}', 'docker.pkg.github.com', github.repository, 'bookstore', github.sha) }}

    - name: Set deployment status
      run: ./.github/scripts/create-deployment.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TARGET_URL: https://bookstore-prod.azurewebsites.net
